Update de_de.json
blay09/FarmingForBlockheads pull request #199
Opened 2023-11-01 18:37 UTC by Wizqok

matching en_us now

2023-11-01 19:08 UTC, BlayTheNinth requested changes

2023-11-01 19:08 UTC, BlayTheNinth commented on shared/src/main/resources/assets/farmingforblockheads/lang/de_de.json
> -  "gui.farmingforblockheads:market.tooltip_saplings": "Setzlinge",
Setzlinge is the vanilla translation for saplings

2023-11-01 19:08 UTC, BlayTheNinth commented on shared/src/main/resources/assets/farmingforblockheads/lang/de_de.json
> -  "gui.farmingforblockheads:market.tooltip_other": "Sonstiges",
Sonstiges seems more fitting than Andere

2023-11-01 21:26 UTC, Wizqok reviewed
changed

2023-11-01 21:27 UTC, Wizqok commented
are you gonna push this also for other branches? 
Br

2023-11-03 13:41 UTC, merged

2023-11-03 13:42 UTC, BlayTheNinth commented
Language updates are released alongside regular updates, so only versions that receive updates from hereon out will include these changes